version: '3.8'

services:
  web:
    build: .
    container_name: snake
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - cloudflare_default

networks:
  cloudflare_default:
    external: true
