version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: snake
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - cloudflare_default

networks:
  cloudflare_default:
    external: true
