version: '3.8'

services:
  web:
    build: .
    container_name: snake
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - cloudflare_default

networks:
  cloudflare_default:
    external: true
